  name: viewer
  run-name: viewer docker package build
  on: [push]

  jobs:
    Builder:
      runs-on: ubuntu-latest
      steps:

        - name: Repository checkout
          uses: actions/checkout@v4

        - name: Log in to Gitea Docker Registry
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login git.norbif.hu -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        - name: Build Docker image
          run: |
            docker build -t git.norbif.hu/midrastil/viewer-frontend:latest frontend
            docker build -t git.norbif.hu/midrastil/viewer-backend:latest comms
            

        - name: Push Docker image
          run: |
            docker push git.norbif.hu/midrastil/viewer-frontend:latest
            docker push git.norbif.hu/midrastil/viewer-backend:latest
